# Get all blogs
GET http://localhost:3003/api/blogs

###

# Post new blog
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
	"title": "Something",
	"author": "Someone",
	"url": "https://google.com",
	"likes": 10
}

###

# Post invalid blog
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
	"author": "Someone",
	"url": "https://google.com",
	"likes": 10
}

###

# Delete invalid id
DELETE http://localhost:3003/api/blogs/notARealID

###

# Post new user
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
	"username": "Testiuser",
	"name": "Testi Käyttäjä",
	"password": "abc123"
}

###

# List all users
GET http://localhost:3003/api/users/

###

# List all blogs
GET http://localhost:3003/api/blogs/

###

# Post new blog
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer token

{
	"title": "Something",
	"author": "Someone",
	"url": "https://google.com",
	"likes": 10
}

###

## Delete blog
DELETE http://localhost:3003/api/blogs/68a2f4cf97c00633c66bfe0a HTTP/1.1


###

# Invalid login
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
	"username": "Non-existent",
	"password": "123"
}

###
# Valid login
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
	"username": "Testiuser",
	"password": "abc123"
}